### ISSUE TITLE
Database Incomplete

### ISSUE THREAD

**Issue by brenns10** [hacsoc/love#1]
The primary issue with CWRU love right now is that our student/faculty database dump is not complete. As a stopgap I implemented 6cd97e36be8930a24df9259c829476f017af67ea which allows admin users to fill out a form and (provided they don't inject SQL :scream:) add a user.  So manually reported missing users can be addressed really quickly now, but that won't help when new students enroll, etc. Having a reliable LDAP import/update flow is an end goal, but there are several things we can do to improve.

- [ ] Update the 500 page to look nicer. In particular using the default layout would be nice, so it still looks Yelpy. Most importantly is a mailto: link so that people know that if they get an Internal Error on their first login, they can email me and I can fix it.
- [x] Do some major work on the user import tasks. The CSV import flow is really odd and slow, and originally it did some logic on "terminating" employees missing from the CSV that ended up consuming all of the instance memory. That was eliminated in 084507a7e2aef436f2c949969df15523625dda76, but I could do a lot more to ensure that we avoid hitting the 10-minute time limit
- [x] Establish a more streamlined process for generating CSV import files from LDAP. In particular, determining attributes to use that will not filter out relevant users is really important.

Long-term, some final solutions look like this:

1. The CSV import process is improved enough that it is reliable on large datasets. A final LDAP import script is written, and each semester the script is run manually, and the result is uploaded and imported. The major benefit here is that, if I get the LDAP conditions right, hopefully everyone will be in the database dump every time. The disadvantage is that the DB will be huge, and autocomplete may suffer.
2. We dynamically look up users on LDAP as they log in, and as people attempt to send them love. This is nice because the DB only increases as needed. The downside is that there will be no autocomplete for missing users until after their first login/first love.  Even more importantly, **we need to switch to appscale to do this** because GAE doesn't allow us to open sockets (necessary for LDAP connections).

**Comment by rockdog** [comment]
Hi brenns10,

just a quick heads-up that while Yelp/love doesn‘t support LDAP out of the box the way we implemented it is: every night we generate a JSON file with all employees from LDAP and save that in an S3 bucket (this is a custom script which is not part of the release). Then we have a cronjob setup to import this JSON file. Of course that way new users don‘t end up in Yelp/love immediately but with at max 1 day delay (which works fine for us). The cron/S3 parts are documented as well in the README.

**Comment by brenns10** [comment]
Thanks @rockdog!  The trouble we're encountering here is mostly with the fact that we're students and don't run the LDAP server ourselves :grimacing:.  Since I don't know the meaning of any of the LDAP attributes or object classes, it's really difficult to filter the data.  It's especially troublesome because as a university with significant churn, we have a lot more "Employees" than Yelp does, and so when I try to import too too many users, I run up against time/memory constraints in the worker instance.

My hope is that we can get to a similar user import process as Yelp (i.e. option number 1), because I don't want to diverge our fork much from upstream.

**Comment by brenns10** [comment]
Updates on this issue:

- Appscale is either off the table or very far down the line for us, so we're stuck with LDAP -> CSV import.
- I've improved the LDAP dump process. The corresponding repository is [brenns10/ldump](https://github.com/brenns10/ldump) and issues with that can be discussed there. For right now, the database dump should be good enough.
- The CSV import process still gives me a lot of trouble. There's enough going on that it should have its own ticket.

For right now, our database is "good enough" and we have enough stopgap measures in place (in particular: 6cd97e36be8930a24df9259c829476f017af67ea, and #3, once we merge it) that I think we can close this issue.
