### ISSUE TITLE
Emails capped at 100 recipients per day

### ISSUE THREAD

**Issue by brenns10** [hacsoc/love#6]
This has not yet been a problem for us; 100 recipients is a lot to go through in a day. However, I believe that we could have bursty traffic (especially if we are doing any amount of PR about this service). It would stink to make a big announcement, get a lot of traffic, and run over our 100 email limit early in the day.

The [SendGrid API](https://cloud.google.com/appengine/docs/python/mail/sendgrid) offers 12,000 monthly emails on their free version, which adds up to 400 per day. That daily count is pretty great, but the best part is that in the event of bursty traffic, we can go way over without risking a service outage for part of a day.

I'd like to stick email behind a simple abstraction layer (probably a single function) that allows us to select an email provider (GAE or SendGrid, or maybe some other some day). Then I'll implement it for SendGrid and set up a free account for us so that we can switch between GAE and SendGrid providers.

One question remaining is, would Yelp be interested in this change once it's implemented and tested? I think it is a worthwhile feature to upstream. Even if Yelp itself won't use it, more flexibility for emails makes it easier for other organizations to use while keeping it on a budget. On that question, I'd like to ping @rockdog and @sjaensch so we don't bother them with a PR they don't want :)

**Comment by sjaensch** [comment]
@brenns10 that sounds like a great feature, go for it!

**Comment by brenns10** [comment]
Implemented, closing.
