### ISSUE TITLE
Potential for abuse

### ISSUE THREAD

**Issue by brenns10** [hacsoc/love#8]
I don't think this is likely but I suppose it is possible for people to send rude and abusive messages through CWRU Love (especially with the private feature so others don't see). I don't want to linger on a remote possibility, but it seems like if nothing else it would be nice to throw in a link at the bottom of the love email telling people that if a message is abusive they should report it. Any thoughts on this?

**Comment by mtbentley** [comment]
Adding a report email/form would be a good idea.  It might have to be followed up with an admin feature to remove comments or block users though.

**Comment by brenns10** [comment]
yeah although I'm going to say that the email would be good for now - if we start having problems, I have the ability to remove users via the GAE console. If abuse becomes a big enough problem that we need to develop features for blocking users and removing love... well that probably is the day that I shut down the service :/

**Comment by brenns10** [comment]
Closing this via #11 unless we encounter any actual reports of problem
